package:
  name: sensorutils
  version: "0.1.0"

source:
  # git_url: https://github.com/USGS-Astrogeology/SensorUtils-Swig.git
  path: ../

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake >=3.10
    - libsensorutils
    - python
    - swig
  host:
    - python
  run:
    - libsensorutils
    - python

test:
  imports:
    - sensorutils
    
about:
  home: https://github.com/USGS-Astrogeology/SensorUtils-Swig
  license: None
summary: "SWIG Wrapper to generate bindings to the Community Sensor Model"
